### ISSUE TITLE
some issues feedback to you

### ISSUE THREAD

**Issue by bau720123** [SanderSoulwax/CDVFrisBrowser#2]
hi @SanderSoulwax 
I am using PGB 3.7 and your latest plugin 0.0.6 with my ipad mini 8.1.3
http://plugins.cordova.io/#/package/nl.frismedia.frisbrowser

according to this
https://github.com/SanderSoulwax/CDVFrisBrowser/blob/master/doc/index.md

[Q1]
it said
statusBarStyle can be "default" (black text) or "lightContent" (white text)
but in fact that I tried many times...
"default" => become "white" title bar
"lightContent" => become "grey" title bar

[Q2]
it said
If you're replacing the buttonImage, make sure that image is added to your xcode-project.
but in fact that I use PFB (not xcode)...
so...how to solve it or determine the "location"
http://www.littlebau.com/01Frisbrowserjpg.jpg
is it possible maybe one day can use the "http" link (http://somedomain/some.png) ?

[Q3]
about the "fontName"
is the "fontName" only have one value => "Futura-Medium" ? (the css name ? or ?)
because I tried different type，such like "Arial"
but it seem look like all the same

[Q4]
about the "fontColor"
it seem not work ...

[Q5]
if I set the "headerBackgroundColor"
well...
no mater which r,g,b value is，the title bar will always become like "green"

**Comment by terrabythia** [comment]
Thanks for your feedback! This plugin was mainly made for a specific project, but then I thought that others might think it would be useful too, so I published it. It's still not in it's 1.0.0 release, so feedback like yours is invaluable at this stage. 

I'm not in the position to verify and fix any of the bugs right now, but maybe later today or tomorrow. 

[Q1] Do you mean that it's actually the other way around? default should be black text, lightContent should be white text. It could be that, when set to default, the global application settings decides which one is used. Will look into this though.

[Q2] I'm not familiar with PFB, but does that also mean you can't open the project in xcode to add additional resources like images? Also, the external resource image is a good idea, will see how I can implement that in the plugin in the future.

[Q3] The font must also be added as a resource in the xcode project or be a default available font. You can see a full list here: http://iosfonts.com/. As you see the fontName for 'Arial' is not just 'Arial', but 'ArialMT'. Can you try this and see if that works?

[Q4] Nothing happens? I have checked my code and that seems to be in order. Will try it myself later though.

[Q5] I found this to be a bug indeed. Have fixed this now, expect to update it (hopefully along with some other bugfixes) tomorrow (0.0.7).

**Comment by bau720123** [comment]
hi @SanderSoulwax 
thanks for your reply
well...

[Q1]
when I set "statusBarStyle" to "default"
http://www.littlebau.com/title1.png
when I set "statusBarStyle" to "lightContent"
http://www.littlebau.com/title2.png

[Q2]
PGB is a cloud build server，so...it don't need eclipse or xcode anymore
ya!!!external resource image is really a good idea

[Q3]
after according to this
http://iosfonts.com/
problem solved， for example，I choose "Futura-MediumItalic" and really become "Italic"
but...
how about the future in android ?
is the "iosfonts" also suit in Android ?

[Q4]
YES!!!
I really tried many times，it seem not work

[Q5]
thanks for your help

[Q6] another suggestion
http://www.littlebau.com/title1.png
you can notice that "The upper left corner" have the default words "close"
if the word can determine by ourself，I think it is more Elasticity to everybody
if the function can come true，is there any "conflict" with the attribute "buttonImage" ?
because it all related to the "close button" (I recommend，Cancel the "buttonImage" attribute and a new attribute that called "buttonName" or etc...)

**Comment by terrabythia** [comment]
I've had some time to work on the bugs you mentioned. Most of them are fixed now, you can expect an update later today.

[Q1] is this not what you would expect? ligtContent means the content (the statusbar text) will have a light (white) color. Default it's black. Just as in your screenshots.

[Q2] To make it possible to also use images that aren't added as a resource, I've added your suggested option to use external images as a fallback. The plugin will automatically recognise that you're using an external image url and set that image. In the first version of this feature there is no retina support yet. You also have to make sure the image is the right size.

[Q3] Glad that's solved!
Also: I have to look into Android. They will definitely not have the exact same font-pack, but maybe you will have to set an Android fallback font-option or something.

[Q4] There was indeed a bug in the fontColor. I've fixed that now.

[Q5] Glad to help ;)

[Q6] This option already exists! I forgot to document this, but you can also set the "buttonTitle" option to change the text.

I will give  you an heads up here when I know for sure the plugin is updated.

**Comment by bau720123** [comment]
hi @SanderSoulwax 
really thanks your reply again
well..

the Q1's suggestion
if can let the statusBarStyle usage method just like the fontColor usage
not just "default" or "lightContent"
for example follow your rule

```
statusBarStyle: {r:x, g:y, b:z}
```

thanks again

**Comment by terrabythia** [comment]
Unfortunately that's not possible on iOS: they limit the content colors to only black or white.

FYI: I've uploaded the new version with the bug fixes to github and the plugin registry. Let me know if you still have any issues.

**Comment by bau720123** [comment]
thanks @SanderSoulwax 
all issues solved !!!
you are awesome !!!

**Comment by terrabythia** [comment]
No problem!
